// export const DELETE_ITEM = 'DELETE_ITEM';
// export const ITEMS_LOADING = 'ITEMS_LOADING';
export const START_LOADING_POST = 'START_LOADING_POST';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const FETCH_POST = 'FETCH_POST';
export const ADD_POST = 'ADD_POST';
export const START_ADDING_POST = 'START_ADDING_POST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const DELETE_POST = 'DELETE_POST'
export const ADD_ABOUT = 'ADD_ABOUT';

export const START_LOADING_COMMENT = 'START_LOADING_COMMENT'
export const LOAD_COMMENT_SUCCESS = 'LOAD_COMMENT_SUCCESS'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'

export const PROFILE_UPDATING_START = 'PROFILE_UPDATING_START'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';